# Server酱（微信通知）配置示例

[monitoring]
# 启用监控
enabled = true

# Server酱配置
[monitoring.serverchan]
send_key = "SCT299918Tjm2hNLuwKRB9DqqHaiDvj3kJ"  # 您的 SendKey
enabled = true

# 通知设置
alert_on_profit = true      # 利润通知
alert_on_error = true       # 错误通知
alert_on_warning = true     # 警告通知

# 利润通知阈值（只通知大于此金额的利润）
min_profit_for_alert = 1_000_000  # 0.001 SOL

# 频率限制（避免通知过于频繁）
rate_limit_ms = 5000  # 5 秒内最多发送一条

# ==================== 通知示例 ====================

# 1. 利润通知示例：
# ✅ 套利成功！
# 
# **净利润**: 0.005000 SOL
# **ROI**: 150.00%
# **Jito Tip**: 0.001000 SOL
# **交易对**: SOL-USDC
# 
# **时间**: 2025-10-20 14:32:15

# 2. 错误通知示例：
# ❌ 错误发生
# 
# Transaction timeout
# 
# **上下文**: JitoExecutor
# **时间**: 2025-10-20 14:35:10

# 3. 熔断通知示例：
# 🚨 熔断器触发！
# 
# 机器人已自动停止交易以保护资金安全。
# 
# **原因**: 连续失败 5 次
# **冷却时间**: 300 秒
# **连续失败**: 5
# **成功率**: 35.0%

# ==================== 注意事项 ====================

# 1. SendKey 获取方式：
#    - 访问 https://sct.ftqq.com/
#    - 微信扫码登录
#    - 在"发送消息"页面获取 SendKey

# 2. 通知接收：
#    - 消息会推送到您的微信"服务通知"
#    - 首次使用可能有 1-2 分钟延迟
#    - 确保微信允许"服务通知"

# 3. 免费额度：
#    - 每天最多 1000 条消息
#    - 对于套利机器人来说完全够用

# 4. 测试方法：
#    - 运行 test-serverchan.js 测试连接
#    - 查看微信是否收到测试消息

# 5. 故障排除：
#    - 如果没收到消息，检查 SendKey 是否正确
#    - 确认微信"服务通知"未被屏蔽
#    - 查看日志中的错误信息

