# 中等资金套利策略配置
# 适合资金量: 1 - 10 SOL
# 风险偏好: 平衡
# 预期收益: 0.0005 - 0.005 SOL/次

[bot]
name = "arbitrage-bot-medium"
network = "mainnet-beta"
dry_run = false

[rpc]
# 中等资金建议使用付费 RPC（QuickNode/Helius）
urls = [
  "https://your-endpoint.quiknode.pro/YOUR_KEY/",  # 修改为您的 RPC
  "https://rpc.helius.xyz/?api-key=YOUR_KEY",
  "https://api.mainnet-beta.solana.com",  # 备用
]
commitment = "processed"
timeout = 30000

[keypair]
path = "${HOME}/.config/solana/id.json"
min_balance_sol = 0.5  # 保留更多余额

# ==================== 经济模型配置 ====================

[economics]
capital_size = "medium"

[economics.cost]
signature_count = 2
compute_units = 400_000
compute_unit_price = 10_000  # 标准优先费
use_flash_loan = false  # 可选使用闪电贷

[economics.profit]
# 利润阈值：标准
min_profit_lamports = 500_000  # 0.0005 SOL
min_roi = 50  # 50% ROI
max_slippage = 0.02  # 2% 滑点
min_liquidity_usd = 5000  # 至少 $5K 流动性

[economics.risk]
# 风险控制：平衡
max_consecutive_failures = 5
max_hourly_loss_lamports = 500_000  # 0.0005 SOL/小时
min_success_rate = 0.4  # 40% 成功率
cooldown_period = 300_000  # 5 分钟冷却

[economics.jito]
# Jito 小费：平衡策略
min_tip_lamports = 10_000  # 0.00001 SOL
max_tip_lamports = 50_000_000  # 0.05 SOL
profit_share_percentage = 20  # 利润的 20%
competition_multiplier = 1.5  # 标准竞争倍数
urgency_multiplier = 1.2  # 适度加急

# ==================== Jupiter Bot 配置 ====================

[jupiter_server]
rpc_url = "${RPC_URL}"
port = 8080
enable_circular_arbitrage = true
max_routes = 3  # 允许更多路由
only_direct_routes = false  # 允许间接路由

[opportunity_finder]
# 代币列表：50-100 个热门代币
mints_file = "./mints-top50.txt"
worker_count = 4  # 使用 4 个 Worker
query_interval_ms = 10  # 10ms 查询间隔（标准）
min_profit_lamports = 500_000
slippage_bps = 50  # 0.5% 滑点

# ==================== 执行器配置 ====================

[execution]
mode = "jito"
trade_amount_sol = 0.5  # 每次交易 0.5 SOL
max_concurrent_trades = 2  # 允许 2 笔并发

[jito]
block_engine_url = "https://mainnet.block-engine.jito.wtf"
auth_keypair_path = "${KEYPAIR_PATH}"
check_jito_leader = true
min_tip_lamports = 10_000
max_tip_lamports = 50_000_000
tip_strategy = "balanced"  # 平衡策略

# ==================== 监控配置 ====================

[monitoring]
enabled = true
webhook_url = "${DISCORD_WEBHOOK_URL}"
alert_on_profit = true
alert_on_error = true
alert_on_warning = true
min_profit_for_alert = 1_000_000  # 0.001 SOL
rate_limit_ms = 5000  # 5 秒

# 性能统计通知（每小时）
performance_stats_interval = 3600000

# ==================== 日志配置 ====================

[logging]
level = "info"
pretty_print = false
file_output = true
log_dir = "./logs"
log_file_name = "medium-capital.log"
console_output = true

# ==================== 安全配置 ====================

[security]
max_daily_trades = 200
max_daily_loss_sol = 1.0
max_single_trade_sol = 1.0

# ==================== 预期表现 ====================

# 基于中等资金策略的预期表现：
# - 机会发现率：20-40 个/小时
# - 执行成功率：50-60%
# - 单次平均利润：0.0005 - 0.002 SOL
# - 预期日收益：0.05 - 0.2 SOL
# - 风险评级：中等
