# ============================================
# Lifinity V2 测试配置
# ============================================
# 此配置用于测试 Lifinity V2 池子的集成
# 包括 2 个已知的高频 Lifinity V2 池子

[websocket]
url = "wss://api.mainnet-beta.solana.com"

[proxy]
enabled = true
host = "127.0.0.1"
port = 7890

# ============================================
# Lifinity V2 池子（来自数据库分析）
# ============================================

# SOL/USDC - 高频使用 (5120 uses)
[[pools]]
address = "DrRd8gYMJu9XGxLhwTCPdHNLXCKHsxJtMpbn62YqmwQe"
name = "SOL/USDC (Lifinity V2)"
pool_type = "lifinity_v2"

# SOL/USDT - 中频使用 (1376 uses)
[[pools]]
address = "5zvhFRN45j9oePohUQ739Z4UaSrgPoJ8NLaS2izFuX1j"
name = "SOL/USDT (Lifinity V2)"
pool_type = "lifinity_v2"

# ============================================
# 参考池子（Raydium AMM V4 - 用于对比）
# ============================================

# USDC/USDT (Raydium V4) - 高流动性稳定币对
[[pools]]
address = "7XawhbbxtsRcQA8KTkHT9f9nc6d69UwqCDh6U5EEbEmX"
name = "USDC/USDT (Raydium V4)"
pool_type = "amm_v4"

