# Rust Pool Cache - 4 New DEX Integration Test Configuration
# 测试 AlphaQ, SolFi V2, HumidiFi, GoonFi 集成

[websocket]
url = "wss://api.mainnet-beta.solana.com"

[proxy]
enabled = true
host = "127.0.0.1"
port = 7890

# ============================================
# Raydium V4 核心池（价格锚定参考）
# ============================================

[[pools]]
address = "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2"
name = "SOL/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "77quYg4MGneUdjgXCunt9GgM1usmrxKY31twEy3WHwcS"
name = "USDC/USDT (Raydium V4)"
pool_type = "amm_v4"

# ============================================
# NEW: AlphaQ 池子 (18% 机会覆盖)
# ============================================
# Program ID: ALPHAQmeA7bjrVuccPsYPiCvsi428SNwte66Srvs4pHA
# Status: ✅ Working - 1.5 updates/sec

[[pools]]
address = "Pi9nzTjPxD8DsRfRBGfKYzmefJoJM8TcXu2jyaQjSHm"
name = "USDT/USDC (AlphaQ)"
pool_type = "alphaq"

[[pools]]
address = "9xPhpwq6GLUkrDBNfXCbnSP9ARAMMyUQqgkrqaDW6NLV"
name = "USDC/USD1 (AlphaQ)"
pool_type = "alphaq"

[[pools]]
address = "6R3LknvRLwPg7c8Cww7LKqBHRDcGioPoj29uURX9anug"
name = "USDS/USDC (AlphaQ)"
pool_type = "alphaq"

# ============================================
# NEW: SolFi V2 池子 (37% 机会覆盖) - 最重要！
# ============================================
# Program ID: SV2EYYJyRz2YhfXwXnhNAevDEui5Q6yrfyo13WtupPF  
# Status: ✅ Working - 6.4 updates/sec (超活跃！)

[[pools]]
address = "65ZHSArs5XxPseKQbB1B4r16vDxMWnCxHMzogDAqiDUc"
name = "USDC/USDT (SolFi V2)"
pool_type = "solfi_v2"

[[pools]]
address = "FkEB6uvyzuoaGpgs4yRtFtxC4WJxhejNFbUkj5R6wR32"
name = "USDC/USDT (SolFi V2) #2"
pool_type = "solfi_v2"

# TODO: 查找 SOL/USDC 和 USDC/SOL 池子地址

# ============================================
# NEW: HumidiFi 池子 (14% 机会覆盖)
# ============================================
# Program ID: 9H6tua7jkLhdm3w8BvgpTn5LZNU7g4ZynDmCiNN3q6Rp
# Status: ⏳ Testing - 需要找到正确的池子地址

[[pools]]
address = "hKgG7iEDRFNsJSwLYqz8ETHuZwzh6qMMLow8VXa8pLm"
name = "JUP/USDC (HumidiFi)"
pool_type = "humidifi"

# TODO: 查找 SOL/USDC (HumidiFi) 高频池地址

# ============================================
# NEW: GoonFi 池子 (6% 机会覆盖)
# ============================================
# Program ID: goonERTdGsjnkZqWuVjs73BZ3Pb9qoCUdBUL17BnS5j
# Status: ✅ Working - 6.2 updates/sec (超活跃！)

[[pools]]
address = "4uWuh9fC7rrZKrN8ZdJf69MN1e2S7FPpMqcsyY1aof6K"
name = "USDC/SOL (GoonFi)"
pool_type = "goonfi"

# ============================================
# Lifinity V2 池子 (4% 机会覆盖)
# ============================================
# Program ID: 2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c

[[pools]]
address = "DrRd8gYMJu9XGxLhwTCPdHNLXCKHsxJtMpbn62YqmwQe"
name = "SOL/USDC (Lifinity V2)"
pool_type = "lifinity_v2"

[[pools]]
address = "5zvhFRN45j9oePohUQ739Z4UaSrgPoJ8NLaS2izFuX1j"
name = "SOL/USDT (Lifinity V2)"
pool_type = "lifinity_v2"

# ============================================
# 配置说明
# ============================================
# 总计：13 个池子
#   - Raydium V4: 2 个 (价格锚定)
#   - AlphaQ: 3 个 (稳定币专家)
#   - SolFi V2: 2 个 (最重要)
#   - HumidiFi: 1 个 (测试中)
#   - GoonFi: 1 个 (USDC/SOL)
#   - Lifinity V2: 2 个 (Oracle 池)
#
# 预期覆盖率：~65% 套利机会
# DEX 数量：6 个
#
# 最后更新：2025-10-27




