# 验证测试配置
# 用于长时间运行以观察真实市场表现

[websocket]
url = "wss://mainnet.helius-rpc.com/?api-key=d261c4a1-fffe-4263-b0ac-a667c05b5683"

[proxy]
enabled = false
host = "127.0.0.1"
port = 7890

# ============================================
# 路由器配置（验证模式）
# ============================================
[router]
# 使用Complete模式以测试全部能力
mode = "complete"

# 极低ROI阈值以观察所有可能的机会
min_roi_percent = 0.01

# 支持最大跳数
max_hops = 6

# 启用拆分优化
enable_split_optimization = true

[router.bellman_ford]
max_iterations = 10
convergence_threshold = 0.0001

[router.split_optimizer]
max_splits = 5
min_split_amount = 100.0
slippage_model = "constant_product"

# ============================================
# 核心池子配置
# ============================================

[[pools]]
address = "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2"
name = "SOL/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "7XawhbbxtsRcQA8KTkHT9f9nc6d69UwqCDh6U5EEbEmX"
name = "SOL/USDT (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "77quYg4MGneUdjgXCunt9GgM1usmrxKY31twEy3WHwcS"
name = "USDC/USDT (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "61R1ndXxvsWXXkWSyNkCxnzwd3zUNB8Q2ibmkiLPC8ht"
name = "SOL/USDC (Raydium CLMM)"
pool_type = "clmm"

[[pools]]
address = "HJiBXL2f4VGZvYprDVgAPRJ4knq6g3vTqRvvPDHxLJSS"
name = "SOL/USDT (Raydium CLMM)"
pool_type = "clmm"

[[pools]]
address = "AVs9TA4nWDzfPJE9gGVNJMVhcQy3V9PGazuz33BfG2RA"
name = "BTC/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "EoNrn8iUhwgJySD1pHu8Qxm5gSQqLK3za4m8xzD2RuEb"
name = "ETH/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "He3iAEV5rYjv6Xf7PxKro19eVrC3QAcdic5CF2D2obPt"
name = "ETH/SOL (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg"
name = "RAY/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "C6tp2RVZnxBPFbnAsfTjis8BN9tycESAT4SgDQgbbrsA"
name = "RAY/SOL (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "2p7nYbtPBgtmY69NsE8DAW6szpRJn7tQvDnqvoEWQvjY"
name = "ORCA/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "8kJqxAbqbPXGH8yCEr4C2DqZHCRnKZX8gKGmceYXMJXv"
name = "JUP/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "BhQEFZCRnWKQ21LEt4DUby7fKynfmLVJcNjfHNqjEF61"
name = "JUP/USDC (Meteora DLMM)"
pool_type = "meteora_dlmm"

[[pools]]
address = "Pi9nzTjPxD8DsRfRBGfKYzmefJoJM8TcXu2jyaQjSHm"
name = "USDT/USDC (AlphaQ)"
pool_type = "alphaq"

[[pools]]
address = "9xPhpwq6GLUkrDBNfXCbnSP9ARAMMyUQqgkrqaDW6NLV"
name = "USDC/USD1 (AlphaQ)"
pool_type = "alphaq"

[[pools]]
address = "6R3LknvRLwPg7c8Cww7LKqBHRDcGioPoj29uURX9anug"
name = "USDS/USDC (AlphaQ)"
pool_type = "alphaq"

[[pools]]
address = "DrRd8gYMJu9XGxLhwTCPdHNLXCKHsxJtMpbn62YqmwQe"
name = "SOL/USDC (Lifinity V2)"
pool_type = "lifinity_v2"

[[pools]]
address = "5zvhFRN45j9oePohUQ739Z4UaSrgPoJ8NLaS2izFuX1j"
name = "SOL/USDT (Lifinity V2)"
pool_type = "lifinity_v2"

[[pools]]
address = "65ZHSArs5XxPseKQbB1B4r16vDxMWnCxHMzogDAqiDUc"
name = "USDC/USDT (SolFi V2)"
pool_type = "solfi_v2"

[[pools]]
address = "FkEB6uvyzuoaGpgs4yRtFtxC4WJxhejNFbUkj5R6wR32"
name = "USDC/USDT (SolFi V2) #2"
pool_type = "solfi_v2"

[[pools]]
address = "hKgG7iEDRFNsJSwLYqz8ETHuZwzh6qMMLow8VXa8pLm"
name = "JUP/USDC (HumidiFi)"
pool_type = "humidifi"

[[pools]]
address = "6n9VhCwQ7EwK6NqFDjnHPzEk6wZdRBTfh43RFgHQWHuQ"
name = "USDC/USDT (HumidiFi)"
pool_type = "humidifi"

[[pools]]
address = "3QYYvFWgSuGK8bbxMSAYkCqE8QfSuFtByagnZAuekia2"
name = "USD1/USDC (HumidiFi)"
pool_type = "humidifi"

[[pools]]
address = "C1MgLojNLWBKADvu9BHdtgzz1oZX4dZ5zGdGcgvvW8Wz"
name = "USDC/JUP (Whirlpool)"
pool_type = "whirlpool"

[[pools]]
address = "22HUWiJaTNph96KQTKZVy2wg8KzfCems5nyW7E5H5J6w"
name = "USDC/USDT (PancakeSwap)"
pool_type = "pancake"

[[pools]]
address = "FLckHLGMJy5gEoXWwcE68Nprde1D4araK4TGLw4pQq2n"
name = "USDC/SOL (TesseraV)"
pool_type = "tesserav"

[[pools]]
address = "Fukxeqx33iqRanxqsAcoGfTqbcJbVdu1aoU3zorSobbT"
name = "USD1/USDC (Stabble)"
pool_type = "stabble"

[[pools]]
address = "BqLJmoxkcetgwwybit9XksNTuPzeh7SpxkYExbZKmLEC"
name = "USD1/USDC (Stabble) #2"
pool_type = "stabble"

[[pools]]
address = "4uWuh9fC7rrZKrN8ZdJf69MN1e2S7FPpMqcsyY1aof6K"
name = "USDC/SOL (GoonFi)"
pool_type = "goonfi"


# 用于长时间运行以观察真实市场表现

[websocket]
url = "wss://mainnet.helius-rpc.com/?api-key=d261c4a1-fffe-4263-b0ac-a667c05b5683"

[proxy]
enabled = false
host = "127.0.0.1"
port = 7890

# ============================================
# 路由器配置（验证模式）
# ============================================
[router]
# 使用Complete模式以测试全部能力
mode = "complete"

# 极低ROI阈值以观察所有可能的机会
min_roi_percent = 0.01

# 支持最大跳数
max_hops = 6

# 启用拆分优化
enable_split_optimization = true

[router.bellman_ford]
max_iterations = 10
convergence_threshold = 0.0001

[router.split_optimizer]
max_splits = 5
min_split_amount = 100.0
slippage_model = "constant_product"

# ============================================
# 核心池子配置
# ============================================

[[pools]]
address = "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2"
name = "SOL/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "7XawhbbxtsRcQA8KTkHT9f9nc6d69UwqCDh6U5EEbEmX"
name = "SOL/USDT (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "77quYg4MGneUdjgXCunt9GgM1usmrxKY31twEy3WHwcS"
name = "USDC/USDT (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "61R1ndXxvsWXXkWSyNkCxnzwd3zUNB8Q2ibmkiLPC8ht"
name = "SOL/USDC (Raydium CLMM)"
pool_type = "clmm"

[[pools]]
address = "HJiBXL2f4VGZvYprDVgAPRJ4knq6g3vTqRvvPDHxLJSS"
name = "SOL/USDT (Raydium CLMM)"
pool_type = "clmm"

[[pools]]
address = "AVs9TA4nWDzfPJE9gGVNJMVhcQy3V9PGazuz33BfG2RA"
name = "BTC/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "EoNrn8iUhwgJySD1pHu8Qxm5gSQqLK3za4m8xzD2RuEb"
name = "ETH/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "He3iAEV5rYjv6Xf7PxKro19eVrC3QAcdic5CF2D2obPt"
name = "ETH/SOL (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg"
name = "RAY/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "C6tp2RVZnxBPFbnAsfTjis8BN9tycESAT4SgDQgbbrsA"
name = "RAY/SOL (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "2p7nYbtPBgtmY69NsE8DAW6szpRJn7tQvDnqvoEWQvjY"
name = "ORCA/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "8kJqxAbqbPXGH8yCEr4C2DqZHCRnKZX8gKGmceYXMJXv"
name = "JUP/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "BhQEFZCRnWKQ21LEt4DUby7fKynfmLVJcNjfHNqjEF61"
name = "JUP/USDC (Meteora DLMM)"
pool_type = "meteora_dlmm"

[[pools]]
address = "Pi9nzTjPxD8DsRfRBGfKYzmefJoJM8TcXu2jyaQjSHm"
name = "USDT/USDC (AlphaQ)"
pool_type = "alphaq"

[[pools]]
address = "9xPhpwq6GLUkrDBNfXCbnSP9ARAMMyUQqgkrqaDW6NLV"
name = "USDC/USD1 (AlphaQ)"
pool_type = "alphaq"

[[pools]]
address = "6R3LknvRLwPg7c8Cww7LKqBHRDcGioPoj29uURX9anug"
name = "USDS/USDC (AlphaQ)"
pool_type = "alphaq"

[[pools]]
address = "DrRd8gYMJu9XGxLhwTCPdHNLXCKHsxJtMpbn62YqmwQe"
name = "SOL/USDC (Lifinity V2)"
pool_type = "lifinity_v2"

[[pools]]
address = "5zvhFRN45j9oePohUQ739Z4UaSrgPoJ8NLaS2izFuX1j"
name = "SOL/USDT (Lifinity V2)"
pool_type = "lifinity_v2"

[[pools]]
address = "65ZHSArs5XxPseKQbB1B4r16vDxMWnCxHMzogDAqiDUc"
name = "USDC/USDT (SolFi V2)"
pool_type = "solfi_v2"

[[pools]]
address = "FkEB6uvyzuoaGpgs4yRtFtxC4WJxhejNFbUkj5R6wR32"
name = "USDC/USDT (SolFi V2) #2"
pool_type = "solfi_v2"

[[pools]]
address = "hKgG7iEDRFNsJSwLYqz8ETHuZwzh6qMMLow8VXa8pLm"
name = "JUP/USDC (HumidiFi)"
pool_type = "humidifi"

[[pools]]
address = "6n9VhCwQ7EwK6NqFDjnHPzEk6wZdRBTfh43RFgHQWHuQ"
name = "USDC/USDT (HumidiFi)"
pool_type = "humidifi"

[[pools]]
address = "3QYYvFWgSuGK8bbxMSAYkCqE8QfSuFtByagnZAuekia2"
name = "USD1/USDC (HumidiFi)"
pool_type = "humidifi"

[[pools]]
address = "C1MgLojNLWBKADvu9BHdtgzz1oZX4dZ5zGdGcgvvW8Wz"
name = "USDC/JUP (Whirlpool)"
pool_type = "whirlpool"

[[pools]]
address = "22HUWiJaTNph96KQTKZVy2wg8KzfCems5nyW7E5H5J6w"
name = "USDC/USDT (PancakeSwap)"
pool_type = "pancake"

[[pools]]
address = "FLckHLGMJy5gEoXWwcE68Nprde1D4araK4TGLw4pQq2n"
name = "USDC/SOL (TesseraV)"
pool_type = "tesserav"

[[pools]]
address = "Fukxeqx33iqRanxqsAcoGfTqbcJbVdu1aoU3zorSobbT"
name = "USD1/USDC (Stabble)"
pool_type = "stabble"

[[pools]]
address = "BqLJmoxkcetgwwybit9XksNTuPzeh7SpxkYExbZKmLEC"
name = "USD1/USDC (Stabble) #2"
pool_type = "stabble"

[[pools]]
address = "4uWuh9fC7rrZKrN8ZdJf69MN1e2S7FPpMqcsyY1aof6K"
name = "USDC/SOL (GoonFi)"
pool_type = "goonfi"















