# 低ROI阈值测试配置
# 用于验证路由器确实能发现机会

[websocket]
url = "wss://mainnet.helius-rpc.com/?api-key=d261c4a1-fffe-4263-b0ac-a667c05b5683"

[proxy]
enabled = false
host = "127.0.0.1"
port = 7890

# ============================================
# 路由器配置（低阈值测试）
# ============================================
[router]
mode = "complete"
min_roi_percent = 0.01  # ← 降低到0.01%便于测试
max_hops = 6
enable_split_optimization = true

[router.bellman_ford]
max_iterations = 10
convergence_threshold = 0.0001

[router.split_optimizer]
max_splits = 5
min_split_amount = 100.0
slippage_model = "constant_product"

# ============================================
# 简化池子配置（仅核心池子用于快速测试）
# ============================================

[[pools]]
address = "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2"
name = "SOL/USDC (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "7XawhbbxtsRcQA8KTkHT9f9nc6d69UwqCDh6U5EEbEmX"
name = "SOL/USDT (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "77quYg4MGneUdjgXCunt9GgM1usmrxKY31twEy3WHwcS"
name = "USDC/USDT (Raydium V4)"
pool_type = "amm_v4"

[[pools]]
address = "DrRd8gYMJu9XGxLhwTCPdHNLXCKHsxJtMpbn62YqmwQe"
name = "SOL/USDC (Lifinity V2)"
pool_type = "lifinity_v2"

[[pools]]
address = "5zvhFRN45j9oePohUQ739Z4UaSrgPoJ8NLaS2izFuX1j"
name = "SOL/USDT (Lifinity V2)"
pool_type = "lifinity_v2"

[[pools]]
address = "65ZHSArs5XxPseKQbB1B4r16vDxMWnCxHMzogDAqiDUc"
name = "USDC/USDT (SolFi V2)"
pool_type = "solfi_v2"






