-- 将DECIMAL类型改为DOUBLE PRECISION以兼容Rust f64

ALTER TABLE arbitrage_opportunities
    ALTER COLUMN input_amount TYPE DOUBLE PRECISION,
    ALTER COLUMN output_amount TYPE DOUBLE PRECISION,
    ALTER COLUMN gross_profit TYPE DOUBLE PRECISION,
    ALTER COLUMN net_profit TYPE DOUBLE PRECISION,
    ALTER COLUMN roi_percent TYPE DOUBLE PRECISION,
    ALTER COLUMN estimated_fees TYPE DOUBLE PRECISION,
    ALTER COLUMN min_roi_threshold TYPE DOUBLE PRECISION,
    ALTER COLUMN actual_profit TYPE DOUBLE PRECISION;

ALTER TABLE arbitrage_steps
    ALTER COLUMN price TYPE DOUBLE PRECISION,
    ALTER COLUMN expected_input TYPE DOUBLE PRECISION,
    ALTER COLUMN expected_output TYPE DOUBLE PRECISION;

ALTER TABLE pool_updates
    ALTER COLUMN price TYPE DOUBLE PRECISION;

ALTER TABLE router_performance
    ALTER COLUMN min_roi_percent TYPE DOUBLE PRECISION;



ALTER TABLE arbitrage_opportunities
    ALTER COLUMN input_amount TYPE DOUBLE PRECISION,
    ALTER COLUMN output_amount TYPE DOUBLE PRECISION,
    ALTER COLUMN gross_profit TYPE DOUBLE PRECISION,
    ALTER COLUMN net_profit TYPE DOUBLE PRECISION,
    ALTER COLUMN roi_percent TYPE DOUBLE PRECISION,
    ALTER COLUMN estimated_fees TYPE DOUBLE PRECISION,
    ALTER COLUMN min_roi_threshold TYPE DOUBLE PRECISION,
    ALTER COLUMN actual_profit TYPE DOUBLE PRECISION;

ALTER TABLE arbitrage_steps
    ALTER COLUMN price TYPE DOUBLE PRECISION,
    ALTER COLUMN expected_input TYPE DOUBLE PRECISION,
    ALTER COLUMN expected_output TYPE DOUBLE PRECISION;

ALTER TABLE pool_updates
    ALTER COLUMN price TYPE DOUBLE PRECISION;

ALTER TABLE router_performance
    ALTER COLUMN min_roi_percent TYPE DOUBLE PRECISION;















